spring.application.name=authservice
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
server.port=9091
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.file.path=logs/authservice
logging.level.com.example.authservice=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
